name: Recreate OCT image

on:
  # Triggers the workflow every 6 hours
  schedule:
    - cron: "0 */6 * * *"

  workflow_dispatch:

jobs:
  recreate-oct-container-image:
    name: Create new OCT container image
    runs-on: ubuntu-24.04
    env:
      SHELL: /bin/bash

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.PULL_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate against Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          # Use a Robot Account to authenticate against Quay.io
          # https://docs.quay.io/glossary/robot-accounts.html
          username: ${{ secrets.QUAY_ROBOT_USER }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Run endpoint verification script
        run: |
          ./scripts/curl-endpoints.sh

      - name: Build and push the latest images for multi-arch
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            TOKEN=${{ secrets.PULL_TOKEN }}
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          no-cache: true
          push: true
          tags: |
            quay.io/testnetworkfunction/oct:latest


      - name: If failed to create the image, send alert msg to dev team.
        if: ${{ failure() }}
        uses: ./.github/actions/slack-webhook-sender
        with:
          message: 'Failed to create official latest OCT image. Please check the logs.'
          slack_webhook: '${{ secrets.SLACK_ALERT_WEBHOOK_URL }}'
